<?php

namespace Database\Seeders;

use App\Models\BoxOrder;
use App\Models\BoxOrderItem;
use App\Models\BoxTemplate;
use App\Models\DailyConsignment;
use App\Models\Partner;
use App\Models\ProductTemplate;
use App\Models\ShopSession;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

class TrendSeeder extends Seeder
{
    /**
     * Generate 30 days of demo data for trend visualization.
     */
    public function run(): void
    {
        $this->command->info('Generating trend data for the last 30 days...');

        // Get existing data or create minimal required data
        $employees = User::where('role', 'employee')->where('is_active', true)->get();
        if ($employees->isEmpty()) {
            $this->command->warn('No active employees found. Creating one...');
            $employees = collect([
                User::create([
                    'name' => 'Kasir Demo',
                    'email' => 'kasir.demo@posita.com',
                    'password' => bcrypt('password'),
                    'role' => 'employee',
                    'is_active' => true,
                ])
            ]);
        }

        $partners = Partner::where('is_active', true)->get();
        if ($partners->isEmpty()) {
            $this->command->warn('No active partners found. Creating one...');
            $partner = Partner::create([
                'name' => 'Mitra Demo',
                'phone' => '08123456789',
                'is_active' => true,
            ]);
            ProductTemplate::create([
                'partner_id' => $partner->id,
                'name' => 'Produk Demo',
                'base_price' => 10000,
                'selling_price' => 15000,
            ]);
            $partners = collect([$partner]);
        }

        $boxTemplates = BoxTemplate::where('is_active', true)->get();
        if ($boxTemplates->isEmpty()) {
            $this->command->warn('No active box templates found. Creating one...');
            $boxTemplates = collect([
                BoxTemplate::create([
                    'name' => 'Box Standar',
                    'description' => 'Box ukuran standar',
                    'price' => 50000,
                    'is_active' => true,
                ])
            ]);
        }

        // Generate data for last 30 days
        for ($day = 30; $day >= 0; $day--) {
            $date = Carbon::now()->subDays($day);

            // Skip some days randomly (weekend effect)
            if ($day > 0 && rand(1, 10) <= 2) {
                continue;
            }

            $this->generateDayData($date, $employees, $partners, $boxTemplates);
        }

        $this->command->info('Trend data generation completed!');
        $this->command->info('Sessions created: ' . ShopSession::count());
        $this->command->info('Box orders created: ' . BoxOrder::count());
    }

    private function generateDayData($date, $employees, $partners, $boxTemplates): void
    {
        // Generate 1-3 shop sessions per day
        $sessionCount = rand(1, 3);

        for ($i = 0; $i < $sessionCount; $i++) {
            $employee = $employees->random();
            $openTime = $date->copy()->setTime(rand(7, 10), rand(0, 59));
            $closeTime = $openTime->copy()->addHours(rand(4, 8));

            $session = ShopSession::create([
                'user_id' => $employee->id,
                'opened_at' => $openTime,
                'closed_at' => $closeTime,
                'opening_cash' => rand(1, 5) * 100000,
                'closing_cash_system' => 0,
                'closing_cash_actual' => 0,
                'status' => 'closed',
                'notes' => 'Generated by TrendSeeder',
            ]);

            // Generate 2-5 consignments per session
            $consignmentCount = rand(2, 5);
            $totalIncome = 0;

            foreach ($partners as $partner) {
                if (rand(1, 10) <= 7) { // 70% chance for each partner
                    $products = ProductTemplate::where('partner_id', $partner->id)->get();

                    foreach ($products->take(rand(1, 2)) as $product) {
                        $qtyInitial = rand(10, 30);
                        $qtySold = rand(0, $qtyInitial);
                        $qtyRemaining = $qtyInitial - $qtySold;
                        $sellingPrice = $product->selling_price ?? ($product->base_price * 1.3);
                        $subtotalIncome = $qtySold * $sellingPrice;

                        DailyConsignment::create([
                            'shop_session_id' => $session->id,
                            'partner_id' => $partner->id,
                            'product_template_id' => $product->id,
                            'product_name' => $product->name,
                            'base_price' => $product->base_price,
                            'selling_price' => $sellingPrice,
                            'qty_initial' => $qtyInitial,
                            'qty_sold' => $qtySold,
                            'qty_remaining' => $qtyRemaining,
                            'subtotal_income' => $subtotalIncome,
                        ]);

                        $totalIncome += $subtotalIncome;
                    }
                }
            }

            // Update session closing cash
            $systemCash = $session->opening_cash + $totalIncome;
            $variance = rand(-5000, 5000);
            $session->update([
                'closing_cash_system' => $systemCash,
                'closing_cash_actual' => $systemCash + $variance,
            ]);
        }

        // Generate 0-3 box orders per day
        $boxOrderCount = rand(0, 3);

        for ($i = 0; $i < $boxOrderCount; $i++) {
            $pickupDate = $date->copy()->addDays(rand(0, 3))->setTime(rand(10, 18), 0);

            // Determine status based on date
            $statuses = ['pending', 'paid', 'completed', 'cancelled'];
            $statusWeights = [1, 3, 4, 1]; // More paid/completed

            if ($date->isPast() && $pickupDate->isPast()) {
                // Past orders should be completed/cancelled
                $status = rand(1, 10) <= 8 ? 'completed' : 'cancelled';
            } else {
                $status = 'pending';
            }

            $template = $boxTemplates->random();
            $quantity = rand(1, 3);
            $totalPrice = $template->price * $quantity;

            $customerNames = ['Budi', 'Ani', 'Citra', 'Dewi', 'Eko', 'Fitri', 'Gita', 'Hendra'];

            $order = BoxOrder::create([
                'customer_name' => $customerNames[array_rand($customerNames)] . ' ' . rand(1, 99),
                'box_template_id' => $template->id,
                'quantity' => $quantity,
                'total_price' => $totalPrice,
                'pickup_datetime' => $pickupDate,
                'status' => $status,
                'payment_proof_path' => in_array($status, ['paid', 'completed']) ? 'demo/proof.jpg' : null,
                'cancellation_reason' => $status === 'cancelled' ? 'Dibatalkan oleh customer' : null,
                'created_at' => $date->copy()->setTime(rand(8, 20), rand(0, 59)),
            ]);

            // Create line items
            $itemCount = rand(1, 3);
            $itemNames = ['Kue Lapis', 'Brownies', 'Cheese Cake', 'Croissant', 'Donat', 'Roti Sobek'];

            for ($j = 0; $j < $itemCount; $j++) {
                $itemQty = rand(1, 5);
                $itemPrice = rand(10, 50) * 1000;

                BoxOrderItem::create([
                    'box_order_id' => $order->id,
                    'product_name' => $itemNames[array_rand($itemNames)],
                    'quantity' => $itemQty,
                    'unit_price' => $itemPrice,
                    'subtotal' => $itemQty * $itemPrice,
                ]);
            }
        }
    }
}
